### ISSUE TITLE
Youtube broke revanced

### ISSUE THREAD

**Issue by hyunlee1o** [SodaWithoutSparkles/revanced-troubleshooting-guide#10]
When i open any video this happens.
![Screenshot_2024-03-30-11-36-01-086_yt rvx noname exe-edit](https://github.com/SodaWithoutSparkles/revanced-troubleshooting-guide/assets/8699204/7c49d135-df44-448d-90ac-10fa78ccedd2)

**Comment by SodaWithoutSparkles** [comment]
https://sodawithoutsparkles.github.io/revanced-troubleshooting-guide/troubleshoot/03-youtube/37/
