### ISSUE TITLE
Suggestions / Issues for the general step-by-step guide

### ISSUE THREAD

**Issue by KobeW50** [SodaWithoutSparkles/revanced-troubleshooting-guide#12]
1. The [Checking versions](https://sodawithoutsparkles.github.io/revanced-troubleshooting-guide/step-by-step-general/02-check-ver/) step is unnecessary. In step 3, the guide should recommend using the feature in the manager that opens a search in the browser for the suggested version. So the user doesn't need to know the suggested version.

2. In step 3 (Getting the files ready), there is no information on downloading the apk variant supported by the arch of the device. For example, you don't want users downloading the x86 variant of a YTM apk.

**Comment by SodaWithoutSparkles** [comment]
1. It seems that the feature from manager is mature enough to be relied on. Manager's method would be made suggested.
2. Thats a good idea. I would also attempt to detect the phone's architecture via js on the next rewrite

-----------

For example, on my phone, these JS code produces interesting results:

```
>> navigator.platform
< 'Linux armv81'

>> navigator.userAgentData.mobile
< true
```

**Comment by KobeW50** [comment]
> I would also attempt to detect the phone's architecture via js on the next rewrite
> 
> -----------
> 
> For example, on my phone, these JS code produces interesting results:
> 
> ```
> >> navigator.platform
> < 'Linux armv81'
> 
> >> navigator.userAgentData.mobile
> < true
> ```

That is so epic
