### ISSUE TITLE
Revanced app

### ISSUE THREAD

**Issue by Aleksandrt6** [SodaWithoutSparkles/revanced-troubleshooting-guide#16]
Please Remove parental warning . Kindly your assistance 
![Screenshot_20240731_080058_YouTube](https://github.com/user-attachments/assets/245fc2e6-8e56-4b20-be3d-589a61f6346a)

**Comment by SodaWithoutSparkles** [comment]
I dont remember this being in my guide.

1. Where did you find it? In what app?
2  This repo is not intended to be a bug report. It is just intended to serve as a tutorial. Any bug reports/feature requests should be done in the revanced repos, not this one.
