### ISSUE TITLE
reference info for when using custom-aapt2 in ReVanced-CLI results in `permission denied`

### ISSUE THREAD

**Issue by 7Grn** [SodaWithoutSparkles/revanced-troubleshooting-guide#18]
can you add reference info on `chmod` in ReVanced-CLI docs
when using custom-aapt2 in the CLI, sometimes get `permission denied` errors cuz don't have execute permission for this(i did this in [Termux](https://discord.com/channels/952946952348270622/954147049832603748/1279510067023974483), so it may work in other environment without doing this).
Linux(or Termux) is `chmod 755(or chmod +x) ./libaapt2.so` is fine
<https://stackoverflow.com/questions/13377606/chmod-recursively>
Windows needs to use icacls
<https://gist.github.com/jaskiratr/cfacb332bfdff2f63f535db7efb6df93/raw/cd784415bd57c62c1f22c46f71bb695764382c81/chmod-400.cmd>

**Comment by SodaWithoutSparkles** [comment]
I dont think I have suggested the use of custom aapt library anywhere. Can you give me a link of where that was mentioned?
