### ISSUE TITLE
No clue what happened, most likely user error

### ISSUE THREAD

**Issue by Wither-Strike** [SodaWithoutSparkles/revanced-troubleshooting-guide#3]
Went with the step-by-step guide. think I did everything right, didn't get any errors at least. At the end I did the export and clicked the install button, still no errors, and I don't see the app anywhere. I think I clicked an open button but I'm not certain, wasn't paying a whole lot of attention because the guide was over and I thought I was done, and as far as I can tell nothing happened. To cover bases, I checked the android app thing by swiping up on the screen, I checked other pages on the home screen, and I looked in the manager which says no apps have been patched. Currently on the latest version of android (as of writing this) on a Pixel 5A. Here because this is where I was linked in the home of your guide, not sure if this is a duplicate or not

**Comment by SodaWithoutSparkles** [comment]
You mean the install prompt appeared, and you clicked install, and the install sliently disappeared?

**Comment by Wither-Strike** [comment]
Maybe, not sure. Did get it installed though by going into files and finding the exported version and installing that. Seems to be working as far as I can tell. No clue what the difference was. And this folks is why you make backups of everything!

**Comment by SodaWithoutSparkles** [comment]
This is why I add the extra step of exporting the apk. Thanks!
