### ISSUE TITLE
Remove the checking compatibility section in the step-by-step guide

### ISSUE THREAD

**Issue by KobeW50** [SodaWithoutSparkles/revanced-troubleshooting-guide#6]
Manually checking the compatibility on [this page](https://sodawithoutsparkles.github.io/revanced-troubleshooting-guide/step-by-step/04-check-compat/) doesn't provide any real benefit. It is simpler to just have a note leading to a troubleshooting page if users get the warning that their device is armv7

**Comment by SodaWithoutSparkles** [comment]
The benefit is avoiding armv7 users continuing further for a fake hope. 

Sorry for the late reply
