### ISSUE TITLE
Add notice where to read the version

### ISSUE THREAD

**Issue by oSumAtrIX** [SodaWithoutSparkles/revanced-troubleshooting-guide#8]
https://sodawithoutsparkles.github.io/revanced-troubleshooting-guide/step-by-step/02-check-ver/ is only telling you which version is recommended, but does not tell you where to find it in ReVanced Manager.

This contributes to people coming back every now and then and ask the same question again on our support platforms repeatedly.

Add a proper notice, as noticable as necessary so the issue mentioned above is mitigated at its best, or remove the section.

**Comment by SodaWithoutSparkles** [comment]
Thank you for your suggestion. A similar section already exist in the "How to check manually" section (collapsed by default) to instruct users on how to check the version on the ReVanced patches website.

![How to check manually.jpg](https://github.com/SodaWithoutSparkles/revanced-troubleshooting-guide/assets/64138578/d539f9a3-d700-4e91-85f6-6b764a234d04)


This was done to be a more general solution as the ReVanced Manager changes layout of the relevant section more often than the website (at least from when I started writing).

Do you think adding the instruction on how to check in manager still necessary? Or maybe un-collapse the section by default?

**Comment by SodaWithoutSparkles** [comment]
Also note that the instruction on how to check with manager is mentioned [in the general version](https://sodawithoutsparkles.github.io/revanced-troubleshooting-guide/step-by-step-general/02-check-ver/).

**Comment by oSumAtrIX** [comment]
The existing system makes people come and ask for the version and prevents us from providing a proper solution that prevents them from doing so, please figure out a solution

**Comment by oSumAtrIX** [comment]
Hi, please figure a solution out on your end til end of the week. Next week I will deploy a solution that satisfied this issue on our end

**Comment by SodaWithoutSparkles** [comment]
I'll try to implement a solution but i dont know what will the effects be. It should be here in 4 hrs.

**Comment by oSumAtrIX** [comment]
The change is insufficient as the added section goes under the radar of most people reading the page inadvertently leading to the same outcome. I am not gonna open a new issue though, feel free to reopen this one and find a suitable solution that solves the problem description above, I'll figure out a solution until next week as described next week otherwise, thanks.

**Comment by SodaWithoutSparkles** [comment]
For now I'll expand that tab by default. Hoping that the arrow is eye-catching enough to tell them. They will inevitably end up at the same menu in step 5 so they will know how to get to that menu anyways.

**Comment by oSumAtrIX** [comment]
If the user reads the version they will jump off the page at that point. If you move the section above the hardcoded version to first teach the real way to obtain the version without having to ask for the current suggested one everytime, it would mitigate the issue good enough hopefully.
Semantical errors still teach the user wrongly about the suggested version as it is referred to as "latest" version. Issues like this are very common on the page and will be handled on our end til next week.

**Comment by SodaWithoutSparkles** [comment]
I've re-ordered the sections as suggested. The word "latest" is now replaced with "suggested" or "latest suggested".

P.S. The version number is dynamically updated by the workflow at https://github.com/SodaWithoutSparkles/revanced-troubleshooting-guide/blob/main/.github%2Fworkflows%2Fversion-and-lastCheck-bump.yml
