### ISSUE TITLE
App crashing on second time opening

### ISSUE THREAD

**Issue by ishaan-nejeeb** [SodaWithoutSparkles/revanced-troubleshooting-guide#9]
Tried to update youtube because of the issue with watch history not being shown. Downloaded version 19.04.37 of youtube and patched it. App opens fine first time. But on opening it again the buy premium popup comes and then the whole app crashes. Tried reinstalling still the same issue. Installed the older version of latched youutbe i had. That is working normally

**Comment by SodaWithoutSparkles** [comment]
Just try to do it a few times. This resolved the issue for me. 

For bug reports go to https://github.com/revanced/revanced-patches. For further support go to the official discord server.
